### PR TITLE
feat: add option to use browser default font

### PR DESCRIPTION
**Pull request by maximousblk**
I originally wanted to add JetBrains Mono since that's what I use but I think this is a more general solution. But if you don't mind, I can add that too.

image

### CODE REVIEW

**Review by sharat87 — APPROVED** [review]
Thank you for your contribution. Yes this generic solution is indeed better. 🍻

**Review by sharat87 — CHANGES_REQUESTED** [review]
Hey @maximousblk, I just realized, this will break backwards compatibility. The current font value choices of people will have been saved to `localStorage` without quotes. Now that we are adding quotes here, the previous option value won't be recognized and everybody will need to set their font option again.

So, can we keep the existing values as it, without the quotes please? For the new option you are adding, let's have the values as `default` and in the generated CSS, let's just check with something like

```js
editorFontOption() === "default" ? "monospace" : `'${editorFontOption()}'`
```

Does that make sense?

**Comment by maximousblk** [comment]
fixed 👍

**Review by sharat87 — APPROVED** [review]

**Comment by sharat87** [comment]
Hey, appreciate the effort but I'm not sure I agree with the last commit. The file now has mixed indentation with tabs and spaces which was one thing I was keen to avoid when formatting the source files. Could you revert this last commit and we should be okay to merge this PR in. I was initially waiting for the CI to see if it works on external PRs but looks like there's something missing there. I'll investigate that separately. Let's merge this feature in though. 😃

**Comment by maximousblk** [comment]
sorry, is there a formatting script that i can run to properly format the files. i did that because the ci was failing because of it bu i guess i mixed up the indents

**Comment by sharat87** [comment]
Oh I see. Nah don't worry about it. I don't have a full linting pipeline that works well just yet, probably time to put some effort there. You're code was already quite good, I don't have any formatting requirements there. 🍻

**Review by sharat87 — APPROVED** [review]

**Pull request merged**
